# -*- coding: utf-8 -*-
# text = """Kỷ niệm 56 năm ngày thành lập ASEAN tại Liên bang Nga và Hà Lan. Ngày 8/8, Đại sứ quán các nước thành viên ASEAN tại Liên bang Nga và Hà Lan đã long trọng tổ chức kỷ niệm 56 năm ngày thành lập Hiệp hội các quốc gia Đông Nam Á (ASEAN).Ngày 8/8, tại Tổ hợp đa chức năng Hà Nội-Moskva (INCENTRA) ở thủ đô Moskva, Đại sứ quán các nước thành viên ASEAN tại Liên bang Nga đã long trọng tổ chức kỷ niệm 56 năm ngày thành lập Hiệp hội các quốc gia Đông Nam Á (ASEAN).Sự kiện này do Đại sứ quán nước hiện đang giữ chức Chủ tịch luân phiên ASEAN là Indonesia chủ trì. Tham dự sự kiện có các Đại sứ và Phó Đại sứ tất cả Đại sứ quán các nước thành viên ASEAN ở Moskva, cũng như đông đảo nhân viên các Đại sứ quán.Sự kiện bắt đầu với nghi lễ thượng cờ ASEAN, các Đại sứ và Phó Đại sứ cùng cất cao tiếng hát khi cờ ASEAN được kéo lên cũng như nhạc bài ca ASEAN vang lên.Tiếp đó các Đại sứ, Phó Đại sứ, cùng phu nhân và thành viên các Đại sứ quán cùng chụp ảnh lưu niệm, tay bắt chéo theo đúng nghi thức đoàn kết của ASEAN.Phát biểu khai mạc sự kiện, Đại sứ Indonesia tại Liên bang Nga, ông Jose Antonio Morato Tavares, nói rằng 56 năm đã qua kể từ khi ASEAN được thành lập ở Bangkok, hiệp hội nay đã lớn mạnh với các nước thành viên có tốc độ phát triển kinh tế nhanh chóng.ASEAN tự hào là hiệp hội góp phần cho hòa bình, ổn định và đã hình thành được một môi trường để phát triển thịnh vượng. ASEAN có thị trường hơn 670 triệu dân mà hơn một nửa số này là những người trẻ tuổi và năng động sẽ góp phần thúc đẩy nền kinh tế của khu vực Đông Nam Á.Dự kiến vào năm 20230, ASEAN sẽ là khu vực kinh tế lớn thứ 4 trên thế giới, chỉ đứng sau Trung Quốc, Mỹ và Ấn Độ.Đại sứ Tavares nhấn mạnh, tất cả các nước thành viên cũng như người dân ASEAN sẽ cùng có lợi khi môi trường thịnh vượng hiện nay tiếp tục được duy trì, và một trong những nhiệm vụ của ASEAN là phải tiếp tục gìn giữ môi trường ổn định và hòa bình hiện nay trong khu vực, tiếp tục hợp tác với tất cả các nước đối tác. [Lào tổ chức trang trọng Lễ thượng cờ kỷ niệm 56 năm thành lập ASEAN]Tiếp sau phần nghi lễ là phần biểu diễn văn nghệ, chơi các trò chơi vui vẻ và thi đấu thể thao. Tham gia chương trình văn nghệ, các cán bộ, nhân viên Đại sứ quán Việt Nam tại Liên bang Nga đem đến tiết mục hát và múa phụ họa “Hello Việt Nam” được khán phòng vỗ tay tán thưởng nhiệt liệt."""
# from nltk import word_tokenize

# print(word_tokenize(text))
import torch 

labels = torch.tensor([0, 2, 3, 4, 1, 1])
print(labels)
labels = labels.view(-1)
print(labels)
